core/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

pages/urls.py
from django.urls import path

from .views import (PageCreateView, PageDeleteView, PageDetailView,
                    PageListView, PageUpdateView, TagIndexView)

pages_patterns = ([
    path('', PageListView.as_view(), name='pages'),
    path('<slug:slug>/<int:pk>/', PageDetailView.as_view(), name='page'),
    path('create/', PageCreateView.as_view(), name='create'),
    path('update/<int:pk>', PageUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PageDeleteView.as_view(), name='delete'),
    # Taggit
    path('tags/<slug:slug>/', TagIndexView.as_view(), name='tagged'),
], 'pages')

webpictures/urls.py
import debug_toolbar
from actions.urls import actions_patterns
from contact.urls import contact_patterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from likes.urls import likes_patterns
from messenger.urls import messenger_patterns
from pages.urls import pages_patterns
from profiles.urls import profiles_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # Django-debug-toolbar
    path('__debug__/', include(debug_toolbar.urls)),
    path('pages/', include(pages_patterns, namespace='pages')),
    # path auth
    path('accounts/', include('django.contrib.auth.urls')),
    # django-social-auth
    path('social-auth/', include('social_django.urls', namespace='social')),
    # path register
    path('accounts/', include('registration.urls')),
    path('profiles/', include(profiles_patterns)),
    path('messenger/', include(messenger_patterns)),
    path('likes/', include(likes_patterns)),
    path('friends/', include(contact_patterns)),
    path('actions/', include(actions_patterns)),
]


# Logic whit server media files in debug mode
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = "core/home.html"

core/templates/core/home.html
{% extends 'core/index.html'%}
{% block title %}Home{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h1 style="margin: 90px"></h1>
    <div class="container has-text-centered">
        <div class="columns is-vcentered">
            <div class="column is-6 ">
                <figure class="image is-5by4">
                    <img src="https://picsum.photos/800/600/?random" alt="Description">
                </figure>
            </div>
            <div class="column is-7">
                <h1 class="title is-2">
                <br>
                    Web Pictures 
                </h1>
                <h2 class="subtitle is-4">
                    The photos are the protagonists.
                </h2>
                    <main role="main">
                        <div class="container">
                            <div class="row mt-3">
                            <div class="col-md-9 mx-auto mb-5">
                                <p>
                                Login <a href="{% url 'login' %}">here</a>.
                                </p>
                                You do not have an account? Register.  
                                {% if request.user.is_authenticated %}
                                    <script>window.location.href = '/pages/'; </script>
                                {% endif %}
                                <a href="{% url 'signup' %}">here</a>.
                            </div>
                            </div>
                        </div>
                    </main>
            </div>
        </div>
    </div>

{% endblock %}

core/templates/core/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}

    <!--Fonts-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!--styles-->
    {% load static %}
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.8.0/css/bulma.min.css" />
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
    <!--js, ajax and jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" ></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <link rel="shortcut icon" type="image/png" href="{% static 'core/favicon.ico' %}"/>
</head>

<body>
    <div class="hero is-fullheight is-default is-bold">
    <div class="hero-head">
        <nav class="navbar bg-light" style="background-color: grey;">
            <div class="container"> 
                <div class="navbar-end">
                    <div class="tabs is-right">
                        <ul>
                        {% if request.path == '/pages/' %}<li class="is-active">{% endif %}
                            <a href="{% url 'pages:pages' %}">Home</a></li>
                        {% if request.user.is_authenticated %}
                            {% if request.path == '/pages/create/' %}<li class="is-active">{% endif %}
                            <a href="{% url 'pages:create' %}">Upload</a></li>
                            {% if request.path == '/messenger/' %}<li class="is-active">{% endif %}
                            <a href="{% url 'messenger:list' %}">Messenger</a></li>
                            {% with "/profiles/"|add:request.user.username|add:"/"  as profile_url  %}
                            {% if request.path == profile_url %}<li class="is-active">{% endif %}
                            <a href="{% url 'profiles:detail' request.user %}">{{request.user|truncatechars:"12"|title}}</a></li>
                            {% endwith %}
                            {% if request.path == '/profiles/' %}<li class="is-active">{% endif %}
                                <a href="{% url 'profiles:profiles' %}">Profiles</a></li>
                            {% if request.path == '/likes/' %}<li class="is-active">{% endif %}
                                <a href="{% url 'actions:actions' %}">Actions</a></li>
                            <a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                            {% if request.path == '/accounts/login/' %}<li class="is-active">{% endif %}
                            <a href="{% url 'login' %}">Login</a></li>
                            {% if request.path == '/accounts/signup/' %}<li class="is-active">{% endif %}
                            <a href="{% url 'signup' %}">Signup</a></li>
                        {% endif %}
                        </ul> 
                    </div>
                </div>
            </nav>
        </div>
       {% block content %}{% endblock  %}
        <h1 style="margin: 35px"></h1>
        <div class="hero-foot">
            <div class="row justify-content-center">
                <p><strong>Web Pictures  </strong> All rigth reserved</p></li><br><br>
            </div>
        </div>
    </body>
</html>