core/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
]

pages/urls.py
from django.urls import path

from .views import (PageCreateView, PageDeleteView, PageDetailView,
                    PageListView, PageUpdateView, TagIndexView)

pages_patterns = ([
    path('', PageListView.as_view(), name='pages'),
    path('<slug:slug>/<int:pk>/', PageDetailView.as_view(), name='page'),
    path('create/', PageCreateView.as_view(), name='create'),
    path('update/<int:pk>', PageUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', PageDeleteView.as_view(), name='delete'),
    # Taggit
    path('tags/<slug:slug>/', TagIndexView.as_view(), name='tagged'),
], 'pages')

webpictures/urls.py
import debug_toolbar
from actions.urls import actions_patterns
from contact.urls import contact_patterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from likes.urls import likes_patterns
from messenger.urls import messenger_patterns
from pages.urls import pages_patterns
from profiles.urls import profiles_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # Django-debug-toolbar
    path('__debug__/', include(debug_toolbar.urls)),
    path('pages/', include(pages_patterns, namespace='pages')),
    # path auth
    path('accounts/', include('django.contrib.auth.urls')),
    # django-social-auth
    path('social-auth/', include('social_django.urls', namespace='social')),
    # path register
    path('accounts/', include('registration.urls')),
    path('profiles/', include(profiles_patterns)),
    path('messenger/', include(messenger_patterns)),
    path('likes/', include(likes_patterns)),
    path('friends/', include(contact_patterns)),
    path('actions/', include(actions_patterns)),
]


# Logic whit server media files in debug mode
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/pages/page_confirm_delete.html
{% extends 'core/index.html'%}
{% block title %}Update{% endblock %}

{% block content %}

{% load crispy_forms_tags %}
<h1 style="margin: 54px"></h1>
<section class="container">
  <div class="row justify-content-center">
    <div class="col-7">
         
      <img src="{{page.image.url}}" class="img-fluid" alt="Responsive image" width="100%">
     
      <form action="" method="post" enctype="multipart/form-data" >{% csrf_token %}
          {{ form|crispy }}
      <div class="text-center">
        <p>Are you sure you want to delete"{{ object }}"?</p>
        <input type="submit" class="btn btn-secondary btn-block" value="Confirm" />
      </div>
      </form>
   </div>
  </div>
</section>

{% endblock %}

pages/templates/pages/page_detail.html
{% extends 'core/index.html'%}
{% block title %}Web Pictures Pics{% endblock %}

{% block content %}
<style>
  .fa  { margin-bottom: 6px; }
  .fa-heart { color:red }
</style>
<h1 style="margin: 35px"></h1>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-7">
            <div class="card" >
                <div class="header">
                    <div class="media">
                        <div class="media-left">
                            <!-- Show avatar for user post-->
                            {% if page.author.avatar %}
                                <a href="{% url 'profiles:detail' page.author %}" >
                                <img class="avatar image is-96x96" src="{{page.author.avatar.url}}"  alt="Placeholder image"></a>
                            {% endif %}
                        </div>
                        <div class="media-content">
                            </p>
                                <a href="{% url 'profiles:detail' page.author %}" ><p class="title is-4" >{{page.author|title}}</p></a>
                            </p>
                                <p class="subtitle is-5">{{page.title}}</p>
                        </div>
                    </div>
                </div>
                    <figure class="image is-4by3">
                        <img src="{{page.image.url}}" alt="Placeholder image">
                    </figure>
                <div class="card-content">
                    <div class="level is-mobile">
                        <div class="level-left">
                            <div class="level-item has-text-centered">
                                {% if user not in page.likes.all %}
                                    <i type="submit" id="btn{{page.id}}" class="fa fa-heart-o fa-lg" name="{{ page.id }}" value="Like" ></i>
                                {% else %}
                                    <i type="submit" id="btn{{page.id}}" class="fa fa-heart fa-lg" name="{{ page.id }}"  value="Like"/>    </i>
                                {% endif %}
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <i class="material-icons">chat_bubble_outline</i>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                {% if request.user != page.author.user %}
                                    <a href="{% url 'messenger:start' page.author.user.username %}"><i class="material-icons">send</i></a><br>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                         <!-- Like_button -->
                        <div class="total_likes{{page.id}}"></div>

                       <script>

                        var likes = document.querySelector('.total_likes{{page.id}}');

                        function showlikes(){
                        if({{ page.total_likes }} > 0){
                            likes.innerHTML="<strong>Likes "+{{ page.total_likes }}+"<strong>";
                        }else{
                            likes.innerHTML="<p>THIS POST DONT HAVE A LIKES, BE THE FIRST."
                        }
                        return true  
                        }

                        showlikes()
                        
                        var btn = $("#btn{{page.id}}")                    
                        btn.click(function(){
                        var pk = $(this).attr('name');
                                                
                        $.ajax({    
                            type: "POST",
                            url: "{% url 'likes:like_button' page.id %}",
                            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                            dataType: "json",
                        
                            success: function(response){
                                var btn = $("#btn{{page.id}}")
                                btn.toggleClass('fa-heart fa-heart-o');
                                $('.total_likes{{page.id}}').html("<strong>Likes "+response.likes_count+"<strong>");
                                console.log({{page.id}})
                            },
                            });
                        })
                    </script>           
                        <!-- End like_button-->
                        <div class="content">
                        </p>
                        <p>{{page.comment|truncatechars:"300"}}</p>
                        <a href="{% url 'profiles:detail' page.author %}" >{{page.author|title}}</a>
                        <time datetime="{{page.created}}">{{page.created}}</time>
                    </p>
                    <!--Taggit-->
                    {% for tag in tags  %}
                        {% if tag in page.tags.all %}
                        <a href="{% url 'pages:tagged' tag.slug %}">#{{tag.name}}</a>
                        {% endif %}
                    {% empty %}
                        <li>No tags</li>
                    {% endfor %}
                    </p>
                    </div>
                    <!--End Taggit-->
                    <div class="card-footer">
                    {% if request.user.is_authenticated and page.author.user == request.user %} 
                    <ul class="nav navbar-nav d-inline-flex">
                        <li class="nav-item">
                        <ul class="list-inline-mb-0">
                            <li class="list-inline-item"><a href="{% url 'pages:update' page.id %}">Edit </a></li>
                            <li class="list-inline-item"><a href="{% url 'pages:delete' page.id %}">Delete</a></li>          
                        </ul>
                    </ul>
                    {% endif %}
                    <!-- Logic of comment likes-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>

{% endblock  %}

pages/templates/pages/page_form.html
{% extends 'core/index.html'%}
{% block title %}Create{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<style>.errorlist{color:red;} label{display:none}</style>
<h1 style="margin: 50px"></h1>
  <section class="container">
    <div class="row justify-content-center">
      <div class="col-7">
        <form action="" method="post" enctype="multipart/form-data" >{% csrf_token %}
          {{ form|crispy }}
          <div class="text-center">
            <input type="submit" class="btn btn-secondary btn-lg btn-block" value="Update" />
          </div>
        </form>
      </div>
    </div>
  </section>

 
{% endblock %}

pages/templates/pages/page_list.html
{% extends 'core/index.html'%}
{% block title %}Web Pictures Pics{% endblock %}
{% load static %}
{% block content %}


<h1 style="margin: 35px"></h1>
{% for page in page_list %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-7">
            <div class="card">
                <div class="header">
                    <div class="media">
                        <div class="media-left">
                            <div style="width: 115px; height: 90px;">
                                <!-- Show avatar for user post-->
                                {% if page.author.avatar %}
                                <a href="{% url 'profiles:detail' page.author %}">
                                    <img class="avatar image is-96x96" src="{{page.author.avatar.url}}"
                                        alt="Placeholder image"></a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="media-content">
                            <br>
                            <a href="{% url 'profiles:detail' page.author %}">
                                <p class="title is-4">{{page.author|title}}</p>
                            </a>
                            <br>
                            <a href="{% url 'pages:page' page.slug page.id %}">
                                <p class="subtitle is-5">{{page.title}}</p>
                            </a>
                        </div>
                    </div>
                </div>
                </p>
                <figure class="image is-4by3">
                    <img src="{{page.image.url}}" alt="Placeholder image">
                </figure>
                <div class="card-content">
                    <div class="level is-mobile">
                        <div class="level-left">
                            <div class="level-item has-text-centered">
                                {% if user not in page.likes.all %}
                                <i type="submit" id="btn{{page.id}}" class="fa fa-heart-o fa-lg" name="{{ page.id }}"
                                    value="Like"></i>
                                {% else %}
                                <i type="submit" id="btn{{page.id}}" class="fa fa-heart fa-lg" name="{{ page.id }}"
                                    value="Like" /> </i>
                                {% endif %}
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <i class="material-icons">chat_bubble_outline</i>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    {% if request.user != page.author.user %}
                                    <a href="{% url 'messenger:start' page.author.user.username %}"><i
                                            class="material-icons">send</i></a><br>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Like_button -->
                    <div class="total_likes{{page.id}}"></div>

                    <script>
                        var likes = document.querySelector('.total_likes{{page.id}}');

                        function showlikes() {
                            if ({
                                    {
                                        page.total_likes
                                    }
                                } > 0) {
                                likes.innerHTML = "<strong>Likes " + {
                                    {
                                        page.total_likes
                                    }
                                } + "<strong>";
                            } else {
                                likes.innerHTML = "<p>THIS POST DONT HAVE A LIKES, BE THE FIRST.</p>"
                            }
                            return true
                        }
                        showlikes()
                        var btn = $("#btn{{page.id}}")
                        btn.click(function () {
                            var pk = $(this).attr('name');

                            $.ajax({
                                type: "POST",
                                url: "{% url 'likes:like_button' page.id %}",
                                data: {
                                    'pk': pk,
                                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                                },
                                dataType: "json",

                                success: function (response) {
                                    var btn = $("#btn{{page.id}}")
                                    btn.toggleClass('fa-heart fa-heart-o');
                                    $('.total_likes{{page.id}}').html("<strong>Likes " + response
                                        .likes_count + "<strong>");
                                    console.log({
                                        {
                                            page.id
                                        }
                                    })
                                },
                            });
                        })
                    </script>
                    <!-- End like_button-->
                    <div class="content">
                        </p>
                        <p>{{page.comment|truncatechars:"300"}}</p>
                        <a href="{% url 'profiles:detail' page.author %}">{{page.author|title}}</a>
                        <time datetime="{{page.created}}">{{page.created}}</time>
                        </p>
                        <!--Taggit-->
                        {% for tag in tags  %}
                        {% if tag in page.tags.all %}
                        <a href="{% url 'pages:tagged' tag.slug %}">#{{tag.name}}</a>
                        {% endif %}
                        {% empty %}
                        <li>No tags</li>
                        {% endfor %}
                        </p>
                    </div>
                    <!--End Taggit-->
                    <div class="card-footer">
                        {% if request.user.is_authenticated and page.author.user == request.user %}
                        <ul class="nav navbar-nav d-inline-flex">
                            <li class="nav-item">
                                <ul class="list-inline-mb-0">
                                    <li class="list-inline-item"><a href="{% url 'pages:update' page.id %}">Edit </a>
                                    </li>
                                    <li class="list-inline-item"><a href="{% url 'pages:delete' page.id %}">Delete</a>
                                    </li>
                                </ul>
                        </ul>
                        {% endif %}
                        <!-- Logic of comment likes-->

                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
    {% endfor %}

    {% endblock  %}

pages/templates/pages/page_update_form.html
{% extends 'core/index.html'%}
{% block title %}Update{% endblock %}

{% block content %}

{% load crispy_forms_tags %}
<style>.errorlist{color:red;} label{display:none}</style>
<h1 style="margin: 30px"></h1>

  <section class="container">
    <div class="row justify-content-center">
      <div class="col-7">
        {% if 'ok' in request.GET %}
        <p style="color:green;">
          Page edited correctly!.
        </p>
          <a href="{% url 'pages:page' page.id page.title|slugify %}"> Click here, if you want watch the result</a>.
        {% endif %}
        <br><br>
          <img src="{{page.image.url}}" class="img-fluid" alt="Responsive image" width="100%">
        
        <form action="" method="post" enctype="multipart/form-data" >{% csrf_token %}
              {{ form|crispy }}
          <div class="text-center">
            <input type="submit" class="btn btn-secondary btn-lg" value="Upgrade" />
            <a class="btn btn-secondary btn-lg" href="{% url 'pages:delete' page.id %}">Delete</a>
          </div>

        </form>
      
      </div>
    </div>
  </section>
<br><br><br>
{% endblock %}

pages/templates/pages/pages_detail.html
{% extends 'pages/pages_list.html'%}

{% block content %}

<div class="columns body-columns">
    <div class="column is-half is-offset-one-quarter">
        <div class="card">
            <div class="header">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-48x48">
                            <img src="https://source.unsplash.com/random/96x96" alt="Placeholder image">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">{{pages.title}}</p>
                        <p class="subtitle is-6">{{pages.author}}</p>
                    </div>
                </div>
            </div>
            <div class="card-image">
                <figure class="image is-4by3">
                    <img class="img-fluid" src="{{pages.image.url}}" alt="">>
                </figure>
            </div>
            <div class="card-content">
                <div class="level is-mobile">
                    <div class="level-left">
                        <div class="level-item has-text-centered">
                            <a href="">
                                <i class="material-icons">favorite_border</i>
                            </a>
                        </div>
                        <div class="level-item has-text-centered">
                            <div>
                                <a href="">
                                    <i class="material-icons">chat_bubble_outline</i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="content">
                    <p>
                        <strong>32 Likes</strong>
                    </p>
                    {{pages.comment|safe}}
                    {% if pages.categories %}
                        <a>{{pages.categories}}</a>.
                        <a href="#">#{{pages.categories}}</a>
                    {% endif %}
                    <br>
                    <time datetime="{{pages.created}}">{{pages.created}}</time>
                </div>
            </div>
            <div class="card-footer">
                <div class="columns is-mobile">
                    <div class="column is-11">
                        <div class="field">
                            <div class="control">
                                <input class="input is-medium" type="text" placeholder="Add a comment . . .">
                            </div>
                        </div>
                    </div>
                    <div class="column has-text-centered">
                        <button class="button">
                            <i class="material-icons">more_horiz</i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
{% endblock %}